### ISSUE TITLE
Memory leak when using the Redis logger

### ISSUE THREAD

**Issue by Naugrimm** [dmachard/go-dnscollector#353]
I suspect a memory leak when using the Redis logger.

The following chart shows the amount of memory our redis instance has used over time:

![Bildschirmfoto 2023-07-24 um 12 03 03](https://github.com/dmachard/go-dnscollector/assets/5753604/6e638d4a-dd5d-4871-8e43-6f3dc330e3cc)

Redis was restarted around 2023-07-23 09:30 to increase `maxmemory`. The drop at the end occurred the `go-dnscollector` process was stopped.

Here is the amount of memory the `go-dnscollector` used in the same timespan:

![Bildschirmfoto 2023-07-24 um 12 06 07](https://github.com/dmachard/go-dnscollector/assets/5753604/bc27979a-f7e4-4ea0-b25a-c666b22920fe)

The following config is in use:

```yaml
global:
  trace:
    verbose: true
  server-identity: "ns-002"
  text-format: "timestamp-rfc3339ns identity operation rcode queryip queryport family protocol length qname qtype latency"
  text-format-delimiter: " "
  text-format-boundary: "\""
multiplexer:
  collectors:
    - name: sniffer-ens7
      afpacket-sniffer:
        port: 53
        device: ens7
      transforms:
        filtering:
          drop-queryip-file: "/opt/dnscollector/drop-queryip-file.conf"
          drop-domain-file: "/opt/dnscollector/drop-domains-regex.conf"
  loggers:
    - name: prometheus
      prometheus:
        listen-ip: 127.0.0.1
        listen-port: 9154
        basic-auth-enable: false
        basic-auth-login: login
        basic-auth-pwd: password
        tls-support: false
        tls-mutual: false
        tls-min-version: 1.2
        cert-file: ""
        key-file: ""
        prometheus-prefix: "dnscollector"
        top-n: 10
        chan-buffer-size: 65535
        histogram-metrics-enabled: true
    - name: redis
      redispub:
        transport: tcp
        remote-address: redis
        remote-port: 6379
        redis-channel: dnscollector

  routes:
    - from: [ sniffer-ens7 ]
      to: [ prometheus, redis ]
```
