### ISSUE TITLE
Filter keep-queryip is not applied on `afpacket-sniffer`

### ISSUE THREAD

**Issue by arvchristos** [dmachard/go-dnscollector#391]
Hello,

Apparently, the `keep-queryip-file` filter is not applied when using `afpacket-sniffer`. I am not certain whether this is a bug or missing functionality.

```yaml
multiplexer:
  collectors:
    - name: sniff
      afpacket-sniffer:
        device: eth0
        port: 53
        chan-buffer-size: 65535
      transforms:
        filtering:
          keep-queryip-file: "/root/godnscollector/keep.txt"
          drop-queryip-file: ""

```
