### ISSUE TITLE
Add configurable CIDR ranges for anonymization

### ISSUE THREAD

**Issue by johnhtodd** [dmachard/go-dnscollector#473]
**Is your feature request related to a problem? Please describe.**
The anonymize-ip feature is nice, but it does not provide any flexibility in what is transmitted. In our network, for instance, we anonymize completely for normal queries - we eliminate all IP address data at the moment. Some people may only want to summarize down to the /24 or /16 level, though.

**Describe the solution you'd like**
Add IPv4 and IPv6 options for setting the CIDR bits to keep in any anonymization transformation process.

**Additional context**
Here's the simplest example of the additional extensions to anonymization.  I suppose the default behavior can be kept by having the default for anonymize-v4bits as "16" - I don't know what the default bits are for v6 in your current structure or even what would be reasonable.

```
transforms:
  user-privacy:
    anonymize-ip: true
    anonymize-v4bits: 24
    anonymize-v6bits: 48
    hash-ip: false
    minimaze-qname: false
```

NOTE: You'll have to execute anonymization _after_ geoIP lookup, otherwise it will lead to very unexpected issues with accuracy in any mapping transforms. You may do that already - just worth mentioning.

Extra credit: There are special cases where we would want to anonymize/aggregate to the BGP-announced prefix level. Adding an additional extension to this and anonymizing to the BGP-advertised prefix would be amazing, but would also require then a source of BGP data.  It might even be possible to read this in from a BGP table dump (unless you wanted to build in a BGP speaker into the code, which would be a significant challenge.)  We use frr, which uses MRT structures (https://docs.frrouting.org/en/latest/packet-dumps.html#packet-binary-dump-format)

**Comment by dmachard** [comment]
PR completed, if you want to remove IP addresses, use the following configuration:

```
transforms:
  user-privacy:
    anonymize-ip: true
    anonymize-v4bits: "/0"
    anonymize-v6bits: "::/0"
```
