### ISSUE TITLE
Add lat/lon to GeoIP data

### ISSUE THREAD

**Issue by johnhtodd** [dmachard/go-dnscollector#513]
**Is your feature request related to a problem? Please describe.**
Having the city, country, region of the origin IP is very useful, but for direct mapping it would be even more useful to have latitude and longitude (lat / lon) added into the data set for immediate mapping instead of having to do a post-transmission lookup again to turn the city/province/nation data back into a lat/lon for mapping use.

This could be located in a mmdb-city-file format, and could even use the same file as the City lookup (but for flexibility, a separate file should be able to be specified - re-using the mmdb-city-file is not a good idea.)  It seems wise to make this an optional data set, as it is not always needed and could be added in the same way that the other GeoIP fields are added as optional data to insert in the geoip data block.

**Describe the solution you'd like**

Configuration:
```
    transforms:
      geoip:
        mmdb-country-file: "/var/lib/maxmind/GeoIP2-Country.mmdb"
        mmdb-city-file: "/var/lib/maxmind/GeoIP2-City.mmdb"
        mmdb-asn-file: "/var/lib/maxmind/GeoLite2-ASN.mmdb"
        mmdb-coordinate-file: "/var/lib/maxmind/GeoIP2-City.mmdb"

```

Result:

```
{
  "geoip": {
    "city": "Portland",
    "continent": "NA",
    "country-isocode": "US",
    "as-number": "7922",
    "as-owner": "Comcast"
    "lat": "45.515"
    "lon": "-122.687"
},
```
