### ISSUE TITLE
Tag/label data is not being added to DNSTAP output

### ISSUE THREAD

**Issue by johnhtodd** [dmachard/go-dnscollector#516]
**Describe the bug**
The tagging information added to other outputs such as JSON file are not being added to DNSTAP relayed messages, or are not recognized. I'm not sure if this is a bug or just if it would be described as "a not implemented expected feature".

**To Reproduce**
Use configuration below to arbitrarily add tags to messages, and then relay them via DNSTAP to another go-dnscollector instance to validate that they are not being included in the messages.

**Expected behavior**
I would expect go-dnscollector to send and then recognize its own tagging data in DNSTAP streams, and be able to parse that data as a receiver. This would be for both customized tagging ("atags:") as well as any other fields that go-dnscollector adds during processing, such as "geoip:" and all the other fields that are dynamically or statically created by transformations.

**Additional context**
Running most recent version, with this simplified configuration (below.)  The output file shows the tag "foo:DMARC" as being added in the JSON summaries.  I ran another go-dnscollector instance on port 59311 to receive the relayed DNSTAP stream with a very simple single output to JSON, and the tags did not appear either as recognized fields or as data in the "extra:" field.  I am fairly certain they are not being sent.

```
pipelines:

  - name: dnsdist-from-outside
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 59310
      chan-buffer-size: 131070
    routes: [ split-test ]

  - name: godnsconnector-next
    dnstap:
      remote-address: 127.0.0.1
      remote-port: 59311

  - name: split-test
    dnsmessage:
      matching:
        include:
          dns.qtype: "TXT"
          dns.qname: "^*.dmarc.*$"
      policy: "drop-unmatched"
    transforms:
      atags:
        tags: [ "foo:DMARC" ]
    routes: [ outputfile,godnsconnector-next ]

  - name: outputfile
    logfile:
      file-path:  "/tmp/dnstap.log"
      max-size: 1000
      max-files: 10
      mode: json
```
