### ISSUE TITLE
Latency doesn't shown when quiet-text: true 

### ISSUE THREAD

**Issue by top-secrett** [dmachard/go-dnscollector#539]
**Describe the bug**
When I enable normalize with quiet-text: true and enable latency, latency doens't shown.
![image](https://github.com/dmachard/go-dnscollector/assets/92435079/6d891ba0-2ee7-46c3-9a63-17a484e0952e)

**To Reproduce**
```
collectors:
  - name: ns-col-ipv4
    afpacket-sniffer:
       port: 53
       device: ens192
       chan-buffer-size: 65535
     transforms:
       latency:
         measure-latency: true
         unanswered-queries: true
         queries-timeout: 2
       normalize:
         qname-lowercase: false
         quiet-text: true
loggers:
  - name: ns-log
     logfile:
        file-path: /var/log/dns/ns4-queries.log
        mode: text
        flush-interval: 1
        max-size: 100000000
        max-files: 0

routes:
    - from: [ ns-col-ipv4 ]
      to: [ ns-log ]
```

**Additional context**
Version: 0.39.0
