### ISSUE TITLE
json mode does not show RDATA for TXT records

### ISSUE THREAD

**Issue by secure-xxx** [dmachard/go-dnscollector#564]
Hello again, best regardness for your work!
I noticed, when json mode is enabled it sometimes does not show the RDATA field, while i requesting TXT record in particular, however for A records it works. Its a bug?

TXT record:
{"network":{"family":"INET","protocol":"UDP","query-ip":"10.99.128.244","query-port":"65352","response-ip":"172.16.0.95","response-port":"3053","ip-defragmented":false,"tcp-reassembled":false},"dns":{"length":64,"opcode":0,"rcode":"NOERROR","qname":"push.apple.com","qtype":"TXT","flags":{"qr":false,"tc":false,"aa":false,"ra":false,"ad":false},"resource-records":{"an":[],"ns":[],"ar":[]},"malformed-packet":false},"edns":{"udp-size":0,"rcode":0,"version":0,"dnssec-ok":0,"options":[]},"dnstap":{"operation":"CLIENT_RESPONSE","identity":"","version":"-","timestamp-rfc3339ns":"2024-01-23T00:18:21.000363172Z","latency":"0.007841"},"powerdns":{"tags":[],"original-request-subnet":"","applied-policy":"","metadata":{}}}

A record output:
{"network":{"family":"INET","protocol":"UDP","query-ip":"10.99.128.12","query-port":"59676","response-ip":"172.16.0.95","response-port":"3053","ip-defragmented":false,"tcp-reassembled":false},"dns":{"length":161,"opcode":0,"rcode":"NOERROR","qname":"init.push.apple.com","qtype":"A","flags":{"qr":false,"tc":false,"aa":false,"ra":false,"ad":false},"resource-records":{"an":[{"name":"init.push-apple.com.akadns.net.","rdatatype":"A","ttl":9,"rdata":"17.188.182.132"},{"name":"init.push-apple.com.akadns.net.","rdatatype":"A","ttl":9,"rdata":"17.188.183.4"},{"name":"init.push-apple.com.akadns.net.","rdatatype":"A","ttl":9,"rdata":"17.188.182.196"},{"name":"init.push-apple.com.akadns.net.","rdatatype":"A","ttl":9,"rdata":"17.188.182.4"},{"name":"init.push-apple.com.akadns.net.","rdatatype":"A","ttl":9,"rdata":"17.188.182.68"}],"ns":[],"ar":[]},"malformed-packet":false},"edns":{"udp-size":0,"rcode":0,"version":0,"dnssec-ok":0,"options":[]},"dnstap":{"operation":"CLIENT_RESPONSE","identity":"","version":"-","timestamp-rfc3339ns":"2024-01-23T00:15:55.000739726Z","latency":"0.002974"},"powerdns":{"tags":[],"original-request-subnet":"","applied-policy":"","metadata":{}}}

**Comment by dmachard** [comment]
Are you using DNStap as input or PowerDNS protobuf ?

**Comment by secure-xxx** [comment]
Sorry, i forgot to tell. In this case Dnsdist 1.8.3 stands at the front and serve requests, send logs to remote logger (go-dns-collector) 

```yaml
    -- Enable remote logging
    rl = newRemoteLogger("127.0.0.1:6000")
    addAction(AllRule(),RemoteLogAction(rl))
    addResponseAction(AllRule(),RemoteLogResponseAction(rl))
```

And then, collector listening
```yaml
    global:
      trace:
        verbose: true
    
    multiplexer:
      # Listen on tcp/6000 for incoming DNSTap protobuf messages from dns servers
      collectors:
        - name: powerdns
          powerdns:
            listen-ip: 0.0.0.0
            listen-port: 6000
      # Exposes prometheus metrics
      loggers:
        - name: console
          stdout:
            mode: json
      # Routes DNS messages from the tap collector to the prometheus logger
      routes:
        - from: [powerdns]
          to: [console]
```
