### ISSUE TITLE
routing loop from configuration should be refused

### ISSUE THREAD

**Issue by dmachard** [dmachard/go-dnscollector#601]
**Describe the bug**

refuses loop routing from config

```
pipelines:
  - name: dnstap
    file-ingestor:
      watch-dir: /tmp
      watch-mode: dnstap
    routing-policy:
      default: [ dnstap ]
```
