### ISSUE TITLE
Error while configuring relabel-configs for Lokiclient logger

### ISSUE THREAD

**Issue by rajmohanram** [dmachard/go-dnscollector#643]
**Describe the bug**
Following error observed while configuing relabel-config for Loki logger. Loki logger configuration as follows:
```
  loggers:
    - name: loki
      lokiclient:
        server-url: "https://grafana-loki.example.com/loki/api/v1/push"
        job-name: "dnscollector"
        mode: "flat-json"
        tls-insecure: true
        tenant-id: fake
        relabel-configs:
          - source_labels: ["__dns_qtype"]
            target_label: "qtype"
```
Error observed while starting the go-dnscollector: 
```
config error: unknown YAML key `source_labels` in configuration
config error: unknown YAML key `source_labels` in configuration
```
**To Reproduce**
Configure the Loki logger as above.

**Expected behavior**
Relabel configuration accepted and send logs to the Loki with the required labels.

**Additional context**
 - version: v0.41.0
