### ISSUE TITLE
Configuration checks breaks freeform keys

### ISSUE THREAD

**Issue by pieterlexis-tomtom** [dmachard/go-dnscollector#676]
**Describe the bug**
The Scalyr logger has 2 configuration settings (`sessioninfo` and `attrs`) that can contain arbitrary key-value pairs. This is extra information sent alongside the data. This is configured as follows:

```yaml
    loggers:
    -   name: scalyr
        scalyrclient:
            apikey: XXXXX
            attrs:
                service: dnstap
                type: queries
            flush-interval: 10
            mode: flat-json
            sessioninfo:
                cloud_provider: Azure
                cloud_region: westeurope
```

When starting go-dnscollector, it errors (key name might differ, based on parsing order):

```
config error: unknown YAML key `cloud_region` in configuration
```

**To Reproduce**
Configure the scalyr logger as shown above, start go-dnscollector.

**Expected behavior**
go-dnscollector starts fine.

**Additional context**
 - Version 0.43.0 and commit 0267e3b47aa374b51df84ceacb61238258d3fdea

These fields in the config are a `map[string]string` and a `map[string]interface{}`. 

https://github.com/dmachard/go-dnscollector/blob/0267e3b47aa374b51df84ceacb61238258d3fdea/pkgconfig/loggers.go#L239-L240

Perhaps these field types should be ignored when converting the config to a map before checking it?
