### ISSUE TITLE
Possibility to query and external service via Web API

### ISSUE THREAD

**Issue by dtouzeau** [dmachard/go-dnscollector#728]
Hi, it could be cool to query API in order to be more flexible.
Possibility of adding a field by API return.
Enable real-time API REST querying of an external service and adding the response to the event provided by a json result with possibility to define a cache by the sent token

Example

```
transforms:
   api:
      url: "https://apiserver:8080/category/%s"
      header: "X-API-KEY: 123456"
      modifier: qname
      result: "id"
      field: "category-id"
      cache: 30s

```

**Describe alternatives you've considered**

**Additional context**
