### ISSUE TITLE
configchecker - invalid message error

### ISSUE THREAD

**Issue by dmachard** [dmachard/go-dnscollector#731]
**Describe the bug**

The DNscollector returns an invalid error 

`main - config error: stanza(index=1) - invalid stanza - unknown key="logfile"`

Invalid config, 

```
pipelines:
  - name: filednstap
    logfile:
      compress-command: null
```
