### ISSUE TITLE
Can't use dnstap file with bind/named ?

### ISSUE THREAD

**Issue by judzk** [dmachard/go-dnscollector#747]
**Describe the bug**
Hi, i trying to use your collector. We have in bind9 DNS, but no matter what i do, i haven't succeded a forwarded log to loki/prometheus. Now i'm trying to use dnstap log file

**To Reproduce**
bind9 conf .
named.conf.options
```
       dnstap {auth; client; resolver; forwarder;};
       dnstap-output file "/var/log/bind/dnstap.log" versions 2;

```

config.yaml
```
pipelines:
  - name: file-dnstap
    file-ingestor:
      watch-dir: /var/log/bind
      watch-mode: dnstap
    routing-policy:
      forward: [ console,prom,loki ]

  - name: console
    stdout:
      mode: text

  - name: prom
    prometheus:
      listen-ip: 0.0.0.0
      listen-port: 8081
      basic-auth-enable: false
      basic-auth-login: admin
      basic-auth-pwd: changeme
      tls-support: false
      tls-mutual: false
      tls-min-version: 1.2
      cert-file: ""
      key-file: ""
      prometheus-prefix: "dnscollector"
      top-n: 10
      chan-buffer-size: 0
      histogram-metrics-enabled: false
      requesters-metrics-enabled: true
      domains-metrics-enabled: true
      noerror-metrics-enabled: true
      servfail-metrics-enabled: true
      nonexistent-metrics-enabled: true
      timeout-metrics-enabled: true
      prometheus-labels: ["stream_id"]
      requesters-cache-size: 250000
      requesters-cache-ttl: 3600
      domains-cache-size: 500000
      domains-cache-ttl: 3600
      noerror-domains-cache-size: 100000
      noerror-domains-cache-ttl: 3600
      servfail-domains-cache-size: 10000
      servfail-domains-cache-ttl: 3600
      nonexistent-domains-cache-size: 10000
      nonexistent-domains-cache-ttl: 3600
      default-domains-cache-size: 1000
      default-domains-cache-ttl: 3600

  - name: loki
    lokiclient:
      server-url: "http://xxxxxxxxxxxx:3100/api/prom/push"
      job-name: "dnscollector"
      mode: "text"
      flush-interval: 5
      batch-size: 1048576
      retry-interval: 10
      text-format: ""
      proxy-url: ""
      tls-insecure: false
      tls-min-version: 1.2
      ca-file: ""
      cert-file: ""
      key-file: ""
      basic-auth-login: ""
      basic-auth-pwd: ""
      basic-auth-pwd-file: ""
      tenant-id: ""
      relabel-configs: []
      chan-buffer-size: 0

```

**Expected behavior**
Forward dnstap log file to loki, prometheus, console

**Additional context**
 - debian 12
- last release of dnscollector
