### ISSUE TITLE
Can't collect logs on GRE tunnel

### ISSUE THREAD

**Issue by top-secrett** [dmachard/go-dnscollector#771]
**Describe the bug**
I use anti-ddos service for ipv4 via gre tunnel and collector can't collect logs

![image](https://github.com/dmachard/go-dnscollector/assets/92435079/6727b2ad-89fb-4292-951b-9cf840213c08)

```
multiplexer:
  collectors:
    - name: col-ipv4
      afpacket-sniffer:
        port: 53
        device: storm1099
        chan-buffer-size: 65535
      transforms:
        normalize:
          qname-lowercase: false
          quiet-text: true

    - name: col-ipv6
      afpacket-sniffer:
        port: 53
        device: ens224
        chan-buffer-size: 65535
      transforms:
        normalize:
          qname-lowercase: false
          quiet-text: true

  loggers:
    - name: log
      logfile:
        file-path: /var/log/dns/queries.log
        mode: text
        flush-interval: 1
        max-size: 100000000
        max-files: 0

  routes:
    - from: [ col-ipv4 ]
      to: [ log ]
    - from: [ col-ipv6 ]
      to: [ log ]
```

**Additional context**
 - Version 1.0.0-beta1

**Comment by dmachard** [comment]
GRE tunnel is not supported, I think the BPF filter need to be updated to suport thaht.
Could you share a small tcpdump network trace ?

**Comment by top-secrett** [comment]
@dmachard 
[tcpdump_gre.txt](https://github.com/user-attachments/files/16156683/tcpdump_gre.txt)

**Comment by dmachard** [comment]
I confirm you, the BPF filter need to be updated to support GRE protocol
Currently only IP4 and IP6 are expected.

![image](https://github.com/dmachard/go-dnscollector/assets/5562930/a4bba744-5b6b-4573-a1a7-279660bbfb19)

**Comment by dmachard** [comment]
> @dmachard [tcpdump_gre.txt](https://github.com/user-attachments/files/16156683/tcpdump_gre.txt)

PCAP file will be more efficient
thanks

**Comment by top-secrett** [comment]
@dmachard 
[dump.zip](https://github.com/user-attachments/files/16163102/dump.zip)

**Comment by top-secrett** [comment]
@dmachard Hello. Any update?

**Comment by dmachard** [comment]
> @dmachard Hello. Any update?

Hi, for now, I'm enjoying my vacation :)
I'll look in a couple of weeks

**Comment by dmachard** [comment]
@top-secrett  
GRE tunnel are now supported for next release 1.3.0
Any feedbacks will be appreciated.

**Comment by top-secrett** [comment]
@dmachard which devide I need to select? storm1099?
Is it right config?
```
multiplexer:
  collectors:
    - name: ns4-col-ipv4
      afpacket-sniffer:
        port: 53
        #xdp-sniffer:
        device: storm1099
        chan-buffer-size: 65535
        enable-gre: true
```

**Comment by dmachard** [comment]
Can you try sniffing the interface under your tunnel first? (ens192 or ens224)

**Comment by dmachard** [comment]
Thank you for your feedback! A new release, v1.3.0-beta2, has been generated. Could you test it?

With the following configuration, you can capture traffic on a GRE interface (e.g., storm1099) in Raw IP mode

```yaml
multiplexer:
  collectors:
    - name: ns4-col-ipv4
      afpacket-sniffer:
        port: 53
        device: storm1099
        chan-buffer-size: 65535
        enable-rawip: true
        enable-gre: false
```

Alternatively, you can use your previous configuration to capture the traffic on the real interface with GRE decoding. However, as you see the captured IPs may not reflect the actual source or destination due to how the GRE traffic is encapsulated.
