### ISSUE TITLE
matching with arrays

### ISSUE THREAD

**Issue by drenton1** [dmachard/go-dnscollector#799]
### Discussed in https://github.com/dmachard/go-dnscollector/discussions/795

Allow using pipelines > dnsmessage > matching when the JSON includes arrays.  For example, using the below pipeline and dnstap JSON we want to only include messages with rdata = 0.0.0.0

```
pipelines:
  - name: filter-messages
    dnsmessage:
      matching:
        include:
          dns.resource-records.an.0.rdata: "0.0.0.0"
``` 

```
{
  "dns": {
    "resource-records": {
      "an": [
        {
          "name": "test.example.com",
          "rdatatype": "A",
          "class": "IN",
          "ttl": 86400,
          "rdata": "0.0.0.0"
        }
      ],
      "ns": [],
      "ar": []
    }
  }
}
```

Thanks
